#!/usr/bin/env node
// Builds js/data/psalms_kjv.js — the Psalms category for the Catechisms mode —
// from two checked-in inputs:
//   dev/data/psalms/kjv_psalms.json   KJV text, public domain (extracted from
//                                     hutima/Lectio-Memorization data/kjv/19.json,
//                                     itself built from aruljohn/Bible-kjv).
//   dev/data/psalms/summaries.json    Original 1–2 sentence summaries, keyed by
//                                     psalm number ("1"…"150").
//   dev/data/psalms/bullets.json      Short practical application bullets for a
//                                     parishioner (2–3 per psalm, same keys).
// Run: node dev/build_psalms.mjs
// The generated js/data/psalms_kjv.js is the working source of truth (see
// CLAUDE.md "How to update content"); re-running overwrites it, so port any
// hand-edits back into the inputs here.
import { readFileSync, writeFileSync } from 'node:fs';

const IN = new URL('data/psalms/', import.meta.url);
const kjv = JSON.parse(readFileSync(new URL('kjv_psalms.json', IN), 'utf8'));
const summaries = JSON.parse(readFileSync(new URL('summaries.json', IN), 'utf8'));
const bullets = JSON.parse(readFileSync(new URL('bullets.json', IN), 'utf8'));

const psalms = kjv.psalms;
if (psalms.length !== 150) throw new Error(`expected 150 psalms, got ${psalms.length}`);

const items = psalms.map((p, i) => {
  if (p.n !== i + 1) throw new Error(`psalm numbering breaks at index ${i} (n=${p.n})`);
  const summary = summaries[String(p.n)];
  if (!summary || typeof summary !== 'string' || !summary.trim()) throw new Error(`Psalm ${p.n}: missing summary`);
  const apply = bullets[String(p.n)];
  if (!Array.isArray(apply) || apply.length < 1 || apply.length > 3 || apply.some(b => !b || !String(b).trim())) {
    throw new Error(`Psalm ${p.n}: needs 1–3 non-empty application bullets`);
  }
  if (!Array.isArray(p.verses) || !p.verses.length) throw new Error(`Psalm ${p.n}: no verses`);
  p.verses.forEach((v, j) => {
    if (v.num !== j + 1) throw new Error(`Psalm ${p.n}: verse numbering breaks at ${j + 1}`);
    if (!v.text || !v.text.trim()) throw new Error(`Psalm ${p.n}:${v.num}: empty verse`);
  });
  return {
    n: p.n,
    title: `Psalm ${p.n}`,
    q: `Psalm ${p.n}`,
    summary: summary.trim(),
    apply: apply.map(b => String(b).trim()),
    verses: p.verses,
    refs: [`Psalm ${p.n}`],
  };
});
const verseCount = items.reduce((n, it) => n + it.verses.length, 0);

const header = `// PCA Ordination & Licensure Study — the 150 Psalms (KJV), a devotional
// reader category for the Catechisms mode. Generated by dev/build_psalms.mjs
// from dev/data/psalms/{kjv_psalms,summaries}.json.
//
// Text: King James Version — PUBLIC DOMAIN (via hutima/Lectio-Memorization
// data/kjv/19.json, built from aruljohn/Bible-kjv). Summaries are original to
// this app. The ESV is available in the reader ONLY through the user's own
// ESV API token at runtime — ESV text is never bundled in this repo.
// Loaded after js/data/catechisms.js (which assigns window.PCA_CATECHISMS).
`;

const body = `(function (global) {
  const cats = (global.PCA_CATECHISMS = global.PCA_CATECHISMS || {});
  cats.psalms = {
    id: 'psalms',
    label: 'Psalms',
    short: 'Psalms',
    kind: 'psalms',
    source: 'King James Version — public domain. ESV available only through your own ESV API token (api.esv.org); ESV text is never bundled.',
    items: ${JSON.stringify(items, null, 1).replace(/\n/g, '\n    ')},
  };
})(typeof window !== 'undefined' ? window : globalThis);
`;

writeFileSync(new URL('../js/data/psalms_kjv.js', import.meta.url), header + body);
console.log(`js/data/psalms_kjv.js written: ${items.length} psalms, ${verseCount} verses`);
