// Builds js/data/subjects/bible_books.js — per-book Bible "Book Summaries"
// (author, date, theme, outline, Christ & significance) supporting the
// syllabus's weekly "Book Outlines / Book Contents" drills. Hand-authored
// content; inputs live in dev/data/bible_books/*.json (one file per division).
//
// Re-run: node dev/build_bible_books.mjs
// The generated .js is the working source of truth; edit the JSON inputs (or
// the generated file for small fixes) and re-run, then run the quality gates:
//   node dev/validate.mjs  &&  node dev/audit.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const SRC = new URL('./data/bible_books/', import.meta.url);

// setKey -> { label, order, file }. Order continues after Bible Content's
// eight sub-decks (orders 1–8); these are orders 9–16.
const DIVISIONS = [
  { key: 'bk-pentateuch', label: 'Pentateuch (Genesis–Deuteronomy)',                 order: 9,  file: '1-pentateuch.json' },
  { key: 'bk-ot-history', label: 'OT History (Joshua–Esther)',                        order: 10, file: '2-ot-history.json' },
  { key: 'bk-ot-poetry',  label: 'OT Poetry & Wisdom (Job–Song of Songs)',            order: 11, file: '3-ot-poetry.json' },
  { key: 'bk-ot-major',   label: 'Major Prophets (Isaiah–Daniel)',                    order: 12, file: '4-major-prophets.json' },
  { key: 'bk-ot-minor',   label: 'Minor Prophets (Hosea–Malachi)',                    order: 13, file: '5-minor-prophets.json' },
  { key: 'bk-gospels-acts', label: 'Gospels & Acts (Matthew–Acts)',                   order: 14, file: '6-gospels-acts.json' },
  { key: 'bk-paul',       label: 'Pauline Epistles (Romans–Philemon)',                order: 15, file: '7-paul.json' },
  { key: 'bk-general',    label: 'General Epistles & Revelation (Hebrews–Revelation)', order: 16, file: '8-general.json' },
];

const SUBJECT = {
  id: 'bible_books',
  label: 'Bible Book Summaries',
  blurb: "Per-book overviews — author, date, theme, and a working outline — for the syllabus's weekly Book Outlines and Book Contents drills.",
  order: 1.5,
  setKeys: DIVISIONS.map(d => d.key),
};

const SETS = {};
let total = 0;
for (const d of DIVISIONS) {
  const cards = JSON.parse(readFileSync(new URL(d.file, SRC), 'utf8'));
  total += cards.length;
  SETS[d.key] = { label: d.label, subject: SUBJECT.id, order: d.order, cards };
}

const banner = `// PCA Ordination & Licensure Study — Bible Book Summaries
// Generated by dev/build_bible_books.mjs. One card per book of the Bible
// (author, date, theme, outline, Christ & significance), grouped into eight
// division sub-decks under a dedicated "Bible Book Summaries" subject. These
// back the 12-week schedule's "Book Outlines / Book Contents" reading drills
// (see js/data/week_plan.js, where each division deck is assigned to a week).
`;

const body = `(function (global) {
  const SETS = ${JSON.stringify(SETS, null, 2)};

  const SUBJECT = ${JSON.stringify(SUBJECT)};

  const data = (global.PCA_DATA = global.PCA_DATA || { subjects: [], sets: {} });
  Object.assign(data.sets, SETS);
  if (!data.subjects.some(s => s.id === SUBJECT.id)) data.subjects.push(SUBJECT);
})(typeof window !== 'undefined' ? window : globalThis);
`;

const OUT = new URL('../js/data/subjects/bible_books.js', import.meta.url);
writeFileSync(OUT, banner + '\n' + body);
console.log(`Wrote ${total} cards across ${DIVISIONS.length} sub-decks to js/data/subjects/bible_books.js`);
