// Generate js/data/subjects/theology_wcf.js — a theology sub-deck that fills
// confessional gaps: for every WCF chapter that no existing theology card or
// quiz question explicitly cites, emit a review card quoting the chapter's
// definitional section (§1) from the extracted public-domain Confession text
// (js/data/wcf.js, built by dev/build_wcf.py).
//
// Run from the repo root:  node dev/build_theology_wcf.mjs
import { writeFileSync } from 'node:fs';

globalThis.window = globalThis;
const root = new URL('..', import.meta.url);
await import(new URL('js/data/subjects/theology.js', root));
await import(new URL('js/data/quiz/theology.js', root));
await import(new URL('js/data/wcf.js', root));

const data = globalThis.PCA_DATA;
const wcf = globalThis.PCA_WCF;
const theo = data.subjects.find(s => s.id === 'theology');

// Chapters already cited anywhere in the theology deck or quiz bank.
const covered = new Set();
const scan = (s) => {
  for (const m of String(s || '').matchAll(/WCF\s+(\d+)/gi)) covered.add(Number(m[1]));
};
for (const k of theo.setKeys) {
  for (const c of (data.sets[k] || { cards: [] }).cards) {
    scan(c.q); scan(c.a); (c.refs || []).forEach(scan);
  }
}
for (const q of globalThis.PCA_QUIZ || []) {
  if (q.subject === 'theology') { scan(q.q); (q.refs || []).forEach(scan); }
}

// A handful of PDF-extraction artifacts survive in the quoted §1 text: proof-
// marker letters glued onto a word (build_wcf.py strips most, but a few slip
// through when their footnote isn't matched) and words split by a stray space.
// Repair the known cases so the confession quote reads correctly.
function fixWcf(t) {
  return t
    .replace(/\bcast of f\b/g, 'cast off')
    .replace(/great d a y\b/g, 'great day')
    .replace(/\bsalvationa\b/g, 'salvation')
    .replace(/\bperishb\b/g, 'perish');
}

// Authored one-line summaries: each card's body is a 17th-century run-on
// sentence quoted verbatim, which the derived teaser can only cut mid-thought.
const SUMMARIES = {
  12: ('All the justified are received into the number of God\'s children: they bear his '
       + 'name, receive the Spirit of adoption, have access to the throne of grace with '
       + 'boldness, and are pitied, protected, provided for, and chastened by him as a '
       + 'Father — never cast off, but sealed to the day of redemption.'),
  13: ('The regenerate are renewed in the whole man through Christ\'s death and '
       + 'resurrection: sin\'s dominion is destroyed, its lusts more and more weakened and '
       + 'mortified, and the saving graces quickened and strengthened unto practical '
       + 'holiness, without which no man shall see the Lord.'),
  18: ('True believers may in this life be certainly assured that they are in a state of '
       + 'grace — an assurance founded on the divine promises, the inward evidences of '
       + 'grace, and the witness of the Spirit; it may be shaken or interrupted, yet '
       + 'believers are never left without the seed of God.'),
  20: ('Christ purchased believers\' freedom from the guilt of sin, God\'s condemning '
       + 'wrath, and the curse of the law. God alone is Lord of the conscience, which he '
       + 'has left free from doctrines and commandments of men contrary to his Word — or, '
       + 'in matters of faith and worship, beside it.'),
  29: ('The Supper was instituted for the perpetual remembrance of Christ\'s one '
       + 'sacrifice — sealing its benefits to true believers, their spiritual nourishment '
       + 'and growth in him, their further engagement to him, and their communion with him '
       + 'and with each other.'),
  31: ('For the better government and further edification of the church there ought to be '
       + 'synods and councils; they settle controversies of faith and cases of conscience '
       + 'ministerially — and since they may err, their decrees bind only as consonant '
       + 'with the Word of God.'),
};

const cards = [];
for (const ch of wcf.chapters) {
  if (covered.has(ch.n)) continue;
  const sec = ch.sections[0];
  const note = ch.sections.length > 1
    ? `\nNote: WCF ${ch.n} has ${ch.sections.length} sections; this card quotes §1 — open the reference chip to read the full chapter.`
    : '';
  cards.push({
    id: `theo-wcf-${String(ch.n).padStart(2, '0')}`,
    q: `What does the Westminster Confession teach in "${ch.title}" (WCF ${ch.n})?`,
    a: `WCF: ${fixWcf(sec.text)}${note}`,
    ...(SUMMARIES[ch.n] ? { summary: SUMMARIES[ch.n] } : {}),
    refs: [`WCF ${ch.n}.1`, ...sec.refs.slice(0, 5)],
  });
}

if (!cards.length) {
  console.log('No uncovered WCF chapters — nothing to generate.');
  process.exit(0);
}

const SET_KEY = 'theo-wcf';
const out = `// PCA Ordination & Licensure Study — Theology: Confession definitions (WCF).
// Generated by dev/build_theology_wcf.mjs from js/data/wcf.js for every WCF
// chapter not explicitly cited elsewhere in the theology content. Loads after
// js/data/subjects/theology.js and appends a sub-deck to that subject.
// Do not hand-edit; re-run the generator instead.
(function (global) {
  const SET = {
    label: ${JSON.stringify('Confession definitions (WCF)')},
    subject: 'theology',
    order: 99,
    cards: ${JSON.stringify(cards, null, 1)}
  };
  const data = (global.PCA_DATA = global.PCA_DATA || { subjects: [], sets: {} });
  data.sets[${JSON.stringify(SET_KEY)}] = SET;
  const subj = data.subjects.find(s => s.id === 'theology');
  if (subj && !subj.setKeys.includes(${JSON.stringify(SET_KEY)})) subj.setKeys.push(${JSON.stringify(SET_KEY)});
})(typeof window !== 'undefined' ? window : globalThis);
`;
const outPath = new URL('js/data/subjects/theology_wcf.js', root);
writeFileSync(outPath, out);
console.log(`wrote js/data/subjects/theology_wcf.js — ${cards.length} cards for WCF chapters: `
  + cards.map(c => c.refs[0].replace('WCF ', '').replace('.1', '')).join(', '));
