// Generates js/data/subjects/catechism_wsc.js — a "Westminster Shorter Catechism"
// subject whose cards are the WSC questions the 12-week study plan assigns,
// grouped into per-week sub-decks. Source: window.PCA_CATECHISMS (js/data/catechisms.js).
// Run from repo root: node <thisfile>
import { readFileSync, writeFileSync } from 'node:fs';

// Load the catechism data (a window-global data file).
globalThis.window = globalThis;
await import('/home/user/PCA_Ordination_Study/js/data/catechisms.js');
const WSC = globalThis.PCA_CATECHISMS.wsc;
const byN = new Map(WSC.items.map(it => [it.n, it]));

// expand "1-3,89-90" → [1,2,3,89,90]
function expand(spec) {
  const out = [];
  for (const part of spec.split(',')) {
    const m = part.trim().match(/^(\d+)\s*-\s*(\d+)$/);
    if (m) { for (let i = +m[1]; i <= +m[2]; i++) out.push(i); }
    else out.push(parseInt(part, 10));
  }
  return out;
}

// One sub-deck per weekly Catechism assignment (the schedule's Catechism column).
const DECKS = [
  { key: 'wsc-wk2',  label: 'WSC 1–3, 89–90',  spec: '1-3,89-90' },
  { key: 'wsc-wk3',  label: 'WSC 4–11',        spec: '4-11' },
  { key: 'wsc-wk4',  label: 'WSC 12–19',       spec: '12-19' },
  { key: 'wsc-wk5',  label: 'WSC 20–28',       spec: '20-28' },
  { key: 'wsc-wk6',  label: 'WSC 29–36',       spec: '29-36' },
  { key: 'wsc-wk7',  label: 'WSC 85–87',       spec: '85-87' },
  { key: 'wsc-wk8',  label: 'WSC 39, 82–84',   spec: '39,82-84' },
  { key: 'wsc-wk10', label: 'WSC 37–38',       spec: '37-38' },
  { key: 'wsc-wk12', label: 'WSC 88, 91–98',   spec: '88,91-98' },
];

const SETS = {};
const seen = new Set();
let order = 1, nCards = 0;
for (const d of DECKS) {
  const cards = [];
  for (const n of expand(d.spec)) {
    const it = byN.get(n);
    if (!it) throw new Error(`WSC ${n} not found`);
    if (seen.has(n)) throw new Error(`WSC ${n} assigned twice`);
    seen.add(n);
    const card = { id: `wsc-${n}`, q: `WSC ${n}. ${it.q}`, a: it.a };
    if (it.refs && it.refs.length) card.refs = it.refs;
    cards.push(card);
    nCards++;
  }
  SETS[d.key] = { label: d.label, subject: 'shorter_catechism', order: order++, cards };
}

const SUBJECT = {
  id: 'shorter_catechism',
  label: 'Westminster Shorter Catechism',
  blurb: "The Shorter Catechism questions the 12-week plan assigns (WSC 1–39, 82–98), as flashcards — grouped by the weekly Catechism assignment.",
  order: 2.6,
  setKeys: DECKS.map(d => d.key),
};

const banner = `// PCA Ordination & Licensure Study — Westminster Shorter Catechism (study-plan cards)
// Generated by dev/build_catechism_wsc.mjs from js/data/catechisms.js. Cards are
// the WSC questions the 12-week schedule assigns (WSC 1–39 and 82–98), grouped
// into per-week sub-decks (the schedule's Catechism column). The full WSC+WLC
// text still lives in the Catechisms study mode; this subject makes the assigned
// questions reviewable as SRS flashcards and selectable per week.
`;
const body = `(function (global) {
  const SETS = ${JSON.stringify(SETS, null, 2)};

  const SUBJECT = ${JSON.stringify(SUBJECT, null, 2)};

  const data = (global.PCA_DATA = global.PCA_DATA || { subjects: [], sets: {} });
  Object.assign(data.sets, SETS);
  if (!data.subjects.some(s => s.id === SUBJECT.id)) data.subjects.push(SUBJECT);
})(typeof window !== 'undefined' ? window : globalThis);
`;
writeFileSync('/home/user/PCA_Ordination_Study/js/data/subjects/catechism_wsc.js', banner + '\n' + body);
console.log(`Wrote ${nCards} WSC cards across ${DECKS.length} per-week sub-decks`);
