// Builds js/data/subjects/bible_books.js — the "Bible Book Summaries" subject.
//
// Each book has a per-book OVERVIEW card (author, date, theme, outline, Christ
// & significance) and, for books of 5+ chapters, a series of chapter-range
// "Book Contents" cards that walk through the book in sections. Together these
// back the syllabus's weekly "Book Outlines / Book Contents" drills. Cards are
// grouped into eight division sub-decks under a dedicated subject.
//
// Inputs (dev/data/bible_books/, one pair per division):
//   <n>-<division>.json           — overview cards (id "bk-<slug>")
//   <n>-<division>.sections.json  — chapter-range cards (id "bk-<slug>-<a>-<b>")
// Within a deck, each book's overview is followed by its section cards in
// chapter order.
//
// Re-run: node dev/build_bible_books.mjs
// The generated .js is the working source of truth; edit the JSON inputs (or
// the generated file for small fixes) and re-run, then run the quality gates:
//   node dev/validate.mjs  &&  node dev/audit.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const SRC = new URL('./data/bible_books/', import.meta.url);

// setKey -> { label, order, file }. Order continues after Bible Content's
// eight sub-decks (orders 1–8); these are orders 9–16.
const DIVISIONS = [
  { key: 'bk-pentateuch', label: 'Pentateuch (Genesis–Deuteronomy)',                 order: 9,  file: '1-pentateuch' },
  { key: 'bk-ot-history', label: 'OT History (Joshua–Esther)',                        order: 10, file: '2-ot-history' },
  { key: 'bk-ot-poetry',  label: 'OT Poetry & Wisdom (Job–Song of Songs)',            order: 11, file: '3-ot-poetry' },
  { key: 'bk-ot-major',   label: 'Major Prophets (Isaiah–Daniel)',                    order: 12, file: '4-major-prophets' },
  { key: 'bk-ot-minor',   label: 'Minor Prophets (Hosea–Malachi)',                    order: 13, file: '5-minor-prophets' },
  { key: 'bk-gospels-acts', label: 'Gospels & Acts (Matthew–Acts)',                   order: 14, file: '6-gospels-acts' },
  { key: 'bk-paul',       label: 'Pauline Epistles (Romans–Philemon)',                order: 15, file: '7-paul' },
  { key: 'bk-general',    label: 'General Epistles & Revelation (Hebrews–Revelation)', order: 16, file: '8-general' },
];

const SUBJECT = {
  id: 'bible_books',
  label: 'Bible Book Summaries',
  blurb: "Per-book overviews plus chapter-range drills — author, date, theme, outline, and book contents — for the syllabus's weekly Book Outlines and Book Contents work.",
  order: 1.5,
  setKeys: DIVISIONS.map(d => d.key),
};

function readJson(name) {
  try { return JSON.parse(readFileSync(new URL(name, SRC), 'utf8')); }
  catch (e) { if (e.code === 'ENOENT') return []; throw e; }
}

// Interleave: for each overview card, append its chapter-range section cards
// (those whose id is "<overview.id>-<start>-<end>") in ascending chapter order.
function interleave(overviews, sections) {
  // Assign each section to the overview with the longest matching "id-" prefix.
  const byOverview = new Map(overviews.map(o => [o.id, []]));
  for (const sec of sections) {
    let best = null;
    for (const o of overviews) {
      if (sec.id.startsWith(o.id + '-') && (!best || o.id.length > best.id.length)) best = o;
    }
    if (!best) throw new Error(`section ${sec.id} matches no overview`);
    byOverview.get(best.id).push(sec);
  }
  const startCh = (sec, ov) => parseInt(sec.id.slice(ov.id.length + 1), 10) || 0;
  const out = [];
  for (const o of overviews) {
    const secs = byOverview.get(o.id).sort((a, b) => startCh(a, o) - startCh(b, o));
    out.push(o, ...secs);
  }
  return out;
}

const SETS = {};
let nOverview = 0, nSection = 0;
for (const d of DIVISIONS) {
  const overviews = readJson(`${d.file}.json`);
  const sections = readJson(`${d.file}.sections.json`);
  nOverview += overviews.length;
  nSection += sections.length;
  SETS[d.key] = { label: d.label, subject: SUBJECT.id, order: d.order, cards: interleave(overviews, sections) };
}

const banner = `// PCA Ordination & Licensure Study — Bible Book Summaries
// Generated by dev/build_bible_books.mjs. Per book: one overview card (author,
// date, theme, outline, Christ & significance) followed by chapter-range
// "Book Contents" cards for books of 5+ chapters. Grouped into eight division
// sub-decks under a dedicated "Bible Book Summaries" subject. These back the
// 12-week schedule's "Book Outlines / Book Contents" reading drills (see
// js/data/week_plan.js, where each division deck is assigned to a week).
`;

const body = `(function (global) {
  const SETS = ${JSON.stringify(SETS, null, 2)};

  const SUBJECT = ${JSON.stringify(SUBJECT)};

  const data = (global.PCA_DATA = global.PCA_DATA || { subjects: [], sets: {} });
  Object.assign(data.sets, SETS);
  if (!data.subjects.some(s => s.id === SUBJECT.id)) data.subjects.push(SUBJECT);
})(typeof window !== 'undefined' ? window : globalThis);
`;

const OUT = new URL('../js/data/subjects/bible_books.js', import.meta.url);
writeFileSync(OUT, banner + '\n' + body);
console.log(`Wrote ${nOverview} overview + ${nSection} section = ${nOverview + nSection} cards across ${DIVISIONS.length} sub-decks`);
