// Generate js/data/subjects/theology_wcf.js — a theology sub-deck that fills
// confessional gaps: for every WCF chapter that no existing theology card or
// quiz question explicitly cites, emit a review card quoting the chapter's
// definitional section (§1) from the extracted public-domain Confession text
// (js/data/wcf.js, built by dev/build_wcf.py).
//
// Run from the repo root:  node dev/build_theology_wcf.mjs
import { writeFileSync } from 'node:fs';

globalThis.window = globalThis;
const root = new URL('..', import.meta.url);
await import(new URL('js/data/subjects/theology.js', root));
await import(new URL('js/data/quiz/theology.js', root));
await import(new URL('js/data/wcf.js', root));

const data = globalThis.PCA_DATA;
const wcf = globalThis.PCA_WCF;
const theo = data.subjects.find(s => s.id === 'theology');

// Chapters already cited anywhere in the theology deck or quiz bank.
const covered = new Set();
const scan = (s) => {
  for (const m of String(s || '').matchAll(/WCF\s+(\d+)/gi)) covered.add(Number(m[1]));
};
for (const k of theo.setKeys) {
  for (const c of (data.sets[k] || { cards: [] }).cards) {
    scan(c.q); scan(c.a); (c.refs || []).forEach(scan);
  }
}
for (const q of globalThis.PCA_QUIZ || []) {
  if (q.subject === 'theology') { scan(q.q); (q.refs || []).forEach(scan); }
}

const cards = [];
for (const ch of wcf.chapters) {
  if (covered.has(ch.n)) continue;
  const sec = ch.sections[0];
  const note = ch.sections.length > 1
    ? `\nNote: WCF ${ch.n} has ${ch.sections.length} sections; this card quotes §1 — open the reference chip to read the full chapter.`
    : '';
  cards.push({
    id: `theo-wcf-${String(ch.n).padStart(2, '0')}`,
    q: `What does the Westminster Confession teach in "${ch.title}" (WCF ${ch.n})?`,
    a: `WCF: ${sec.text}${note}`,
    refs: [`WCF ${ch.n}.1`, ...sec.refs.slice(0, 5)],
  });
}

if (!cards.length) {
  console.log('No uncovered WCF chapters — nothing to generate.');
  process.exit(0);
}

const SET_KEY = 'theo-wcf';
const out = `// PCA Ordination & Licensure Study — Theology: Confession definitions (WCF).
// Generated by dev/build_theology_wcf.mjs from js/data/wcf.js for every WCF
// chapter not explicitly cited elsewhere in the theology content. Loads after
// js/data/subjects/theology.js and appends a sub-deck to that subject.
// Do not hand-edit; re-run the generator instead.
(function (global) {
  const SET = {
    label: ${JSON.stringify('Confession definitions (WCF)')},
    subject: 'theology',
    order: 99,
    cards: ${JSON.stringify(cards, null, 1)}
  };
  const data = (global.PCA_DATA = global.PCA_DATA || { subjects: [], sets: {} });
  data.sets[${JSON.stringify(SET_KEY)}] = SET;
  const subj = data.subjects.find(s => s.id === 'theology');
  if (subj && !subj.setKeys.includes(${JSON.stringify(SET_KEY)})) subj.setKeys.push(${JSON.stringify(SET_KEY)});
})(typeof window !== 'undefined' ? window : globalThis);
`;
const outPath = new URL('js/data/subjects/theology_wcf.js', root);
writeFileSync(outPath, out);
console.log(`wrote js/data/subjects/theology_wcf.js — ${cards.length} cards for WCF chapters: `
  + cards.map(c => c.refs[0].replace('WCF ', '').replace('.1', '')).join(', '));
